[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_hello_api = "9uVWMyg6PGuLwWUYtA3vY2ubt6JiY5gJRcbHhCW4cXVz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
